### ISSUE TITLE
Supplied resource is not a valid cURL handle resource

### ISSUE THREAD

**Issue by kosolapus** [Eseath/sypexgeo#5]
```
curl_close($ch);
if (!$result) {
            $this->error('Download failed: ' . curl_error($ch));
            return;
        }        
```
in \src\Commands\SxGeoUpdate.php:173
curl should be closed after curl_error

**Comment by RozMakc** [comment]
там проблема с проверкой ссл сертификата, и не только, я так понимаю никто не занимается пакетом(
я добавил у меня заработало:
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

**Comment by kosolapus** [comment]
> там проблема с проверкой ссл сертификата, и не только, я так понимаю никто не занимается пакетом(
> я добавил у меня заработало:
> curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

Да там не только, чел пытается ошибку курла забрать после его закрытия)
Просто строчки местами поменяй и все будет огонь (иначе при любой ошибке курла все плохо будет)
